### ISSUE TITLE
Possible mistake in Stoer–Wagner blog

### ISSUE THREAD

**Issue by chubei** [thomasjungblut/tjungblut-graph#18]
Hi Thomas,

I was reading your [Stoer–Wagner algorithm blog](https://blog.thomasjungblut.com/graph/mincut/mincut/) today. First of all thank you for creating such a beatifully written blog. While the code is correct, I may have found a mistake (typo?) in it. You wrote

> end up with a graph that only has two vertices and this is where we stop the algorithm

and

> until it only contains two vertices

while we should run `MinimumCutPhase` until the graph has only one vertex.

Please forgive me if my understsanding is wrong. Thanks again for the blog!

**Comment by thomasjungblut** [comment]
@chubei thanks for reading :) and sorry for the late reply! 

Indeed: 
https://github.com/thomasjungblut/tjungblut-graph/blob/master/src/de/jungblut/graph/partition/StoerWagnerMinCut.java#L97C41-L97C41

Where we're merging the s and t always at the end, which results in a graph with a single vertex. 

I re-worded the sections you've referenced to be more clear:
https://github.com/thomasjungblut/thomasjungblut.com/commit/d318cecd49c97f3823bcff9a981bd543677d90f5

Thanks again for the report, much appreciated :)
